const GH = 'https://raw.githubusercontent.com/Mattjhagen/NorthStarRecovery/main/readings/';

export const READINGS = [
  {
    id: 'what_is_cma',
    title: 'What is CMA?',
    description: 'An introduction to Crystal Meth Anonymous — who we are, how we work, and what brings us together.',
    audio: require('./readings/What_is_CMA/what_is_cma.mp3'),
    pdfUrl: `${GH}What_is_CMA/What_is_CMA_2022.pdf`,
    icon: 'compass-outline',
    durationEst: '~5 min',
  },
  {
    id: 'there_is_hope',
    title: 'There is Hope',
    description: 'A reminder for anyone who has ever wondered if recovery is possible for them.',
    audio: require('./readings/There_is_Hope/there_is_hope.mp3'),
    pdfUrl: `${GH}There_is_Hope/There%20is%20Hope.txt`,
    icon: 'sunny-outline',
    durationEst: '~4 min',
  },
  {
    id: 'are_you_a_tweaker',
    title: 'Are You a Tweaker?',
    description: 'A candid and gentle look at the patterns of meth use — and what they can tell us.',
    audio: require('./readings/Are_You_a_Tweaker/are_you_a_tweaker.mp3'),
    pdfUrl: `${GH}Are_You_a_Tweaker/are_you_a_tweaker_2025.pdf`,
    icon: 'help-circle-outline',
    durationEst: '~8 min',
  },
  {
    id: 'i_can_stay_sober',
    title: 'I Can Stay Sober',
    description: 'Practical encouragement for staying connected to recovery when it gets hard.',
    audio: require('./readings/I_Can_Stay_Sober/i_can_stay_sober.mp3'),
    pdfUrl: `${GH}I_Can_Stay_Sober/i_can_stay_sober.pdf`,
    icon: 'shield-checkmark-outline',
    durationEst: '~3 min',
  },
  {
    id: 'today_i_can',
    title: 'Today I Can',
    description: 'A daily affirmation reading for the beginning or end of the day.',
    audio: require('./readings/Today_I_can/today_i_can.mp3'),
    pdfUrl: `${GH}Today_I_can/today_i_can.pdf`,
    icon: 'today-outline',
    durationEst: '~4 min',
  },
  {
    id: 'the_12_steps',
    title: 'The 12 Steps',
    description: 'A plan of action — the twelve steps of Crystal Meth Anonymous, with reflection.',
    audio: require('./readings/The_12_Steps/the_12_steps.mp3'),
    pdfUrl: `${GH}The_12_Steps/The-Twelve-Steps-A-Plan-of-Action-2022b.pdf`,
    icon: 'list-outline',
    durationEst: '~10 min',
  },
  {
    id: 'the_12_traditions',
    title: 'The 12 Traditions',
    description: 'How CMA groups stay healthy, unified, and welcoming — the traditions that hold us together.',
    audio: require('./readings/12_Traditions/12_traditions.mp3'),
    pdfUrl: `${GH}12_Traditions/The_Twelve_Traditions_2022b.pdf`,
    icon: 'people-circle-outline',
    durationEst: '~7 min',
  },
];
