const CF = process.env.EXPO_PUBLIC_CLOUDFRONT_SOUNDSCAPES || 'https://d10rkhd3bzdolj.cloudfront.net/soundscapes/';

export function soundscapeUri(name) {
  return { uri: `${CF}${encodeURIComponent(name)}.wav` };
}

export const SOUNDSCAPES = [
  {
    id: 'binaural_breath',
    name: 'Binaural Breath & Echoes',
    category: 'Ambient',
    icon: 'headset-outline',
    description: 'Theta wave binaural pulses tuned for deep nervous system calming and craving reduction.',
    duration: 'Continuous loop',
  },
  {
    id: 'bamboo_stillness',
    name: 'Bamboo Stillness',
    category: 'Nature',
    icon: 'leaf-outline',
    description: 'Gentle wind filtering through bamboo stalks in a tranquil Japanese garden.',
    duration: 'Continuous loop',
  },
  {
    id: 'inner_stillness',
    name: 'Inner Stillness',
    category: 'Ambient',
    icon: 'radio-button-off-outline',
    description: 'Low-frequency resonant drone that grounds somatic anxiety and restlessness.',
    duration: 'Continuous loop',
  },
  {
    id: 'infinite_stillness',
    name: 'Infinite Stillness',
    category: 'Ambient',
    icon: 'infinite-outline',
    description: 'Expansive ethereal pads providing an open, spacious mental environment.',
    duration: 'Continuous loop',
  },
  {
    id: 'stillness',
    name: 'Stillness',
    category: 'Ambient',
    icon: 'ellipse-outline',
    description: 'A pure, steady tonal soundscape for deep meditation and present-moment awareness.',
    duration: 'Continuous loop',
  },
  {
    id: 'synthesized_stillness',
    name: 'Synthesized Stillness',
    category: 'Ambient',
    icon: 'pulse-outline',
    description: 'Analog synthesizer warmth with subtle organic drifting frequencies.',
    duration: 'Continuous loop',
  },
  {
    id: 'emerald_glade',
    name: 'Emerald Glade',
    category: 'Nature',
    icon: 'leaf',
    description: 'Quiet pine forest atmosphere with distant gentle birds and rustling needles.',
    duration: 'Continuous loop',
  },
  {
    id: 'forest_flow',
    name: 'Forest Flow',
    category: 'Nature',
    icon: 'water-outline',
    description: 'Clear mountain stream water flowing smoothly over rounded river rocks.',
    duration: 'Continuous loop',
  },
  {
    id: 'sacred_grove',
    name: 'Sacred Grove',
    category: 'Nature',
    icon: 'flower-outline',
    description: 'Ancient cedar canopy with soft acoustic resonance and natural silence.',
    duration: 'Continuous loop',
  },
  {
    id: 'verdant_breath',
    name: 'Verdant Breath',
    category: 'Nature',
    icon: 'flower',
    description: 'Slow meadow breezes carrying rhythmic natural white noise for sleep.',
    duration: 'Continuous loop',
  },
  {
    id: 'rain_veil',
    name: 'Rain Veil',
    category: 'Rain',
    icon: 'rainy-outline',
    description: 'Delicate rain falling through summer leaves, creating a soft acoustic curtain.',
    duration: 'Continuous loop',
  },
  {
    id: 'soft_night_rain',
    name: 'Soft Night Rain',
    category: 'Rain',
    icon: 'rainy',
    description: 'Gentle night-time rain shower soothing racing thoughts before sleep.',
    duration: 'Continuous loop',
  },
  {
    id: 'soft_night_rainfall',
    name: 'Soft Night Rainfall',
    category: 'Rain',
    icon: 'rainy',
    description: 'Continuous smooth nocturnal precipitation for deep restorative rest.',
    duration: 'Continuous loop',
  },
  {
    id: 'soft_night_rainfall_loopable',
    name: 'Soft Night Rainfall (Loopable)',
    category: 'Rain',
    icon: 'rainy',
    description: 'Seamless loop crafted specifically for overnight sleep sound therapy.',
    duration: 'Continuous loop',
  },
  {
    id: 'seamless_loop_ambient_rainfall',
    name: 'Seamless Loop Ambient Rainfall',
    category: 'Rain',
    icon: 'rainy-outline',
    description: 'Evenly distributed rainfall frequencies with zero abrupt transitions.',
    duration: 'Continuous loop',
  },
  {
    id: 'seamlessly_loopable_soft_night_rain',
    name: 'Seamlessly Loopable Soft Night Rain',
    category: 'Rain',
    icon: 'rainy-outline',
    description: 'Filtered rain texture ideal for background focus or calming bedtime rituals.',
    duration: 'Continuous loop',
  },
  {
    id: 'steady_rainfall',
    name: 'Steady Rainfall',
    category: 'Rain',
    icon: 'thunderstorm-outline',
    description: 'Medium rainfall with satisfying acoustic depth for masking tinnitus or noise.',
    duration: 'Continuous loop',
  },
  {
    id: 'window_patter',
    name: 'Window Patter',
    category: 'Rain',
    icon: 'rainy-outline',
    description: 'Raindrops steadily tapping against a glass windowpane in a quiet room.',
    duration: 'Continuous loop',
  },
  {
    id: 'distant_thunder',
    name: 'Distant Thunder',
    category: 'Rain',
    icon: 'thunderstorm',
    description: 'Rolling low thunder murmurs on the horizon accompanied by gentle rain.',
    duration: 'Continuous loop',
  },
  {
    id: 'distant_rumble',
    name: 'Distant Rumble',
    category: 'Atmospheric',
    icon: 'cloudy-outline',
    description: 'Deep sub-bass acoustic rumble mimicking the safety of a cozy storm shelter.',
    duration: 'Continuous loop',
  },
  {
    id: 'expansive_void',
    name: 'Expansive Void',
    category: 'Atmospheric',
    icon: 'planet-outline',
    description: 'Deep space atmospheric texture designed to quiet rumination and mental chatter.',
    duration: 'Continuous loop',
  },
  {
    id: 'glass_echoes_in_orbit',
    name: 'Glass Echoes in Orbit',
    category: 'Atmospheric',
    icon: 'planet',
    description: 'Crystalline harmonic reflections floating across a wide stereo field.',
    duration: 'Continuous loop',
  },
  {
    id: 'the_deep_blanket',
    name: 'The Deep Blanket',
    category: 'Atmospheric',
    icon: 'cloudy',
    description: 'Warm low-pass filtered audio blanket providing sensory relief and comfort.',
    duration: 'Continuous loop',
  },
  {
    id: 'submerged_comfort',
    name: 'Submerged Comfort',
    category: 'Atmospheric',
    icon: 'water-outline',
    description: 'Muffled underwater ambience replicating the safety of the womb.',
    duration: 'Continuous loop',
  },
  {
    id: 'shadow_textures',
    name: 'Shadow Textures',
    category: 'Atmospheric',
    icon: 'moon-outline',
    description: 'Dark ambient tonal pads that soothe late-night cravings and solitude.',
    duration: 'Continuous loop',
  },
  {
    id: 'chrome_velocity',
    name: 'Chrome Velocity',
    category: 'Electronic',
    icon: 'flash-outline',
    description: 'Uplifting modern electronic soundscape that builds gentle forward momentum.',
    duration: 'Continuous loop',
  },
  {
    id: 'copper_resonance',
    name: 'Copper Resonance',
    category: 'Electronic',
    icon: 'radio-outline',
    description: 'Metallic bell harmonics and sustained bronze resonances for centering.',
    duration: 'Continuous loop',
  },
  {
    id: 'velvet_pulse',
    name: 'Velvet Pulse',
    category: 'Electronic',
    icon: 'pulse',
    description: 'Soft 60 BPM rhythmic pulse that syncs with resting human heart rate.',
    duration: 'Continuous loop',
  },
  {
    id: 'elevation',
    name: 'Elevation',
    category: 'Electronic',
    icon: 'arrow-up-outline',
    description: 'Ascending chord progressions inspiring hope and renewed clarity.',
    duration: 'Continuous loop',
  },
];
