import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import './PublicSite.css';

const CMA_DIRECTORY = 'https://www.crystalmeth.org/cma-meeting-directory/';
const sections = [
  ['Scope', 'This policy describes the public website at cmameet.site and future Northstar Recovery app features when they are made available. It does not apply to Crystal Meth Anonymous, individual meetings, Zoom, or any other third-party site or service.'],
  ['Information this site does not intentionally collect', 'This marketing site is designed without analytics, advertising pixels, cookies for tracking, account registration, contact forms, or newsletter signup. We do not intentionally collect your name, recovery history, location, meeting attendance, or messages through this site.'],
  ['Future app information', 'If app features are enabled, Northstar may process account or profile details you choose to provide, device and push-notification tokens, meeting-related data needed to provide a requested feature, and messages you choose to send. Those features will be presented with their own in-app notices when available.'],
  ['How information would be used', 'Feature-dependent information would be used to operate and secure the requested service, deliver meeting reminders or messages you choose to receive, respond to support requests, and maintain or improve the app.'],
  ['Service providers and sharing', 'Future feature-dependent services may use providers such as AWS for hosting and storage, Expo for app delivery or notifications, and Zoom or another meeting provider when a meeting uses that provider. We would share information only as needed to provide the feature, comply with law, protect people and services, or as part of a business transfer. We do not sell personal information.'],
  ['Retention and security', 'We would retain feature-dependent information only for as long as reasonably needed for the service, legal obligations, dispute resolution, and enforcement. No service can guarantee absolute security; please do not send sensitive information unless the relevant feature clearly supports it.'],
  ['Your choices and requests', 'You can decline optional app permissions, disable notifications in your device settings, and choose not to use future account or messaging features. To request access to or deletion of information associated with a future app feature, contact support@cmameet.site. We may need enough information to verify and fulfill a request.'],
  ['Children', 'Northstar is not directed to children under 13, and we do not knowingly collect personal information from children under 13.'],
  ['International transfers', 'If future app services are used, information may be processed in countries other than where you live, including where our providers operate.'],
  ['Third-party meetings and CMA', 'CMA listings, third-party meeting providers, and sites linked from Northstar have their own privacy practices. Please review their policies before using their services. Northstar is independent and is not affiliated with, endorsed by, or sponsored by Crystal Meth Anonymous.'],
  ['Changes and contact', 'We may update this policy as Northstar evolves. We will post the revised date here. Questions can be sent to support@cmameet.site.']
];

export default function PrivacyPolicy() { return <main className="ns-site ns-policy"><header className="ns-header"><Link className="ns-back" to="/"><ArrowLeft size={17} /> Back to Northstar</Link><Link className="ns-wordmark" to="/"><span className="ns-mark" aria-hidden="true"><span /><i /></span><span>northstar <b>/ CMA MEET</b></span></Link></header><article className="ns-policy-sheet"><p className="ns-kicker">Privacy policy</p><h1>Plain language.<br /><em>Clear boundaries.</em></h1><div className="ns-dates"><span>Effective date: August 13, 2026</span><span>Last updated: August 13, 2026</span></div><p className="ns-policy-intro">Your privacy matters. This policy explains what this public site does—and does not—do with information.</p>{sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<p className="ns-policy-links"><Link to="/">Return home</Link><a href={CMA_DIRECTORY} target="_blank" rel="noreferrer">Official CMA meeting directory <ExternalLink size={14} /></a></p></article></main>; }
